apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2 
kind: StatefulSet 
metadata: 
  name: java-deployment-new
spec: 
  selector: 
    matchLabels: 
      app: javanew
  replicas: 2 # tells deployment to run 2 pods matching the template 
  template:
    metadata: 
      labels: 
        app: javanew 
    spec: 
      containers: 
      - name: javanew 
        image: imageacr.azurecr.io/csandhya8/springbootmavenjunitsample:#{Release.Artifacts._csandhya8_springbootmavenjunitsample.BuildId}#
        resources:
          limits:
           cpu: "1"
          requests:
           cpu: "0.5"
        ports: 
        - containerPort: 8080
      imagePullSecrets:
      - name: autodeploy      
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: java-service-new
spec: 
  selector: 
    app: javanew 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 80 
  type: LoadBalancer 
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
    name: java-deployment-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: StatefulSet
    name: java-deployment-new
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 85
